### import libraries

In [1]:
import json
import pandas as pd
import numpy as np

### load data

In [2]:
movie_info_list=json.load(open( 'movie_info.json','r'))

In [3]:
movie_info_list[0]

{'title': 'Snow White and the Seven Dwarfs',
 'Directed by': ['David Hand',
  'Perce Pearce',
  'William Cottrell',
  'Larry Morey',
  'Wilfred Jackson',
  'Ben Sharpsteen'],
 'Story by': ['Ted Sears',
  'Richard Creedon',
  'Otto Englander',
  'Dick Rickard',
  'Earl Hurd',
  'Merrill De Maris',
  'Dorothy Ann Blank',
  'Webb Smith'],
 'Based on': ['"', 'Snow White', '"', 'by the', 'Brothers Grimm'],
 'Produced by': 'Walt Disney',
 'Starring': ['Adriana Caselotti',
  'Roy Atwell',
  'Pinto Colvig',
  'Otis Harlan',
  'Scotty Mattraw',
  'Billy Gilbert',
  'Eddie Collins'],
 'Music by': ['Frank Churchill', 'Leigh Harline', 'Paul Smith'],
 'Production company': 'Walt Disney Productions',
 'Distributed by': 'RKO Radio Pictures',
 'Release dates': ['December 21, 1937 ( Carthay Circle Theatre )',
  'February 4, 1938 (United States)'],
 'Running time': '83 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget': '$1.5 million',
 'Box office': '$418 million'}

### convert runnung time into integer

In [4]:
def minutes_to_integer(running_time):
    if running_time == "N/A":
        return None
    
    if isinstance(running_time, list):
        return int(running_time[0].split(" ")[0])
    else:
        return int(running_time.split(" ")[0])

In [5]:
for movie in movie_info_list:
    movie['Running time (int)'] = minutes_to_integer(movie.get('Running time', "N/A"))

In [6]:
print([movie.get('Running time (int)') for movie in movie_info_list])

[83, 88, 126, 74, 64, 70, 42, 65, 71, 75, 94, 73, 75, 82, 68, 74, 96, 75, 84, 77, 92, 69, 81, 60, 127, 93, 76, 75, 73, 85, 81, 70, 90, 80, 75, 84, 83, 72, 97, 75, 104, 93, 105, 95, 97, 134, 69, 92, 126, 79, 97, 128, 73, 91, 105, 98, 130, 89, 93, 67, 98, 100, 118, 103, 110, 80, 79, 91, 91, 97, 118, 139, 131, 92, 87, 116, 93, 114, 110, 131, 101, 110, 84, 78, 75, 164, 106, 110, 99, 113, 108, 102, 85, 91, 93, 100, 100, 79, 96, 113, 89, 118, 92, 88, 92, 87, 93, 93, 93, 90, 83, 96, 88, 89, 91, 93, 92, 97, 100, 100, 89, None, 91, 112, 115, 95, 91, 97, 104, 74, 77, 104, 128, 101, 94, 104, 90, 100, 88, 93, 98, 112, 84, 97, 97, 114, 96, 97, 109, 83, 90, 107, 96, 103, 91, 95, 105, 113, 80, 101, 90, 74, 90, 89, 110, 74, 93, 84, 83, 69, 77, 107, 93, 88, 108, 84, 121, 89, 104, 90, 86, 84, 108, 107, 96, 98, 105, 109, 94, 106, 102, 69, 88, 102, 102, 97, 111, 92, 100, 96, 96, 78, 81, 108, 89, 99, 89, 81, 92, 100, 89, 79, 91, 81, 101, 104, 103, 86, 106, 74, 93, 92, 98, 76, 95, 72, 93, 87, 70, 93, 87, 128, 72, 77, 82, 86, 95, 114, 93, 83, 83, 88, 78, 70, 112, 66, 92, 75, 77, 79, 72, 82, 104, 70, 75, 113, 100, 78, 83, 69, 96, 115, 86, 92, 65, 100, 73, 73, 68, 128, 86, 75, 88, 68, 96, 104, 95, 74, 72, 88, 75, 61, 117, 94, 80, 100, 143, 96, 64, 87, 85, 87, 50, 74, 136, 78, 85, 65, 76, 40, 120, 84, 113, 67, 115, 67, 131, 100, 79, 68, 95, 97, 72, 100, 100, 76, 68, 67, 120, 81, 143, 72, 118, 40, 72, 120, 99, 82, 117, 72, 150, 104, 73, 76, 92, 69, 70, 95, 95, 169, 111, 85, 82, 87, 110, 107, 124, 74, 82, 150, 98, 77, 91, 100, 112, 93, 78, 96, 99, 76, 98, 97, 99, 101, 96, 89, 90, 107, 82, 101, 96, 88, 97, 108, 85, 104, 116, 103, 109, 74, 79, 123, 108, 100, 125, None, 84, 90, 88, 109, 89, 104, 137, 106, 63, 88, 103, 93, 132, 77, 96, 93, 100, 89, 87, 75, 101, 130, 77, 104, 149, 92, 81, 102, 125, 107, 78, 77, 124, 97, 84, 127, 81, 102, 124, 129, 76, 106, 82, 130, 95, 154, 94, 117, 108, 106, 99, 113, 97, 118, 103, 124, 107, 161, 86, 129, 76, 129, 102, None, 162, 114, 105, 110, 118, 104, 99, 112, 131, 112, 76, 128, 100, 118, 119, 104, 100, 103, 114, 99, 102, 107, 78, 86, 95, 160, 85, 100, 95, 115, 110, 122, 101, 121, 95, 107, 134, 95, 127, 102, 58, 108, 82, 100, 107, 91, 84, 97, 105, 105, 111, 105, 103, 119, 102, 75, 77, 109, 109, 105, 135, 101, 101, 154, 123, 90, 95, 62, None, None, None, None, 107, 102, None, None, None, 81, 70, None, 90, 93, 91, 78, 124, None, 107, None, 79, 508, 108, 102, 468, 108]

### convert budget and box office to numbers

In [7]:
for movie in movie_info_list:
    print(movie.get('Budget'))

$1.5 million
$2.6 million
$2.28 million
$600,000
$950,000
$858,000
None
$788,000
None
$1.35 million
$2.125 million
None
$1.5 million
$1.5 million
None
$2.2 million
$1.8 million
$3 million
None
$4 million
$2 million
$300,000
$1.8 million
None
$5 million
None
$4 million
None
None
None
None
None
None
$700,000
None
None
None
None
None
$6 million
under $1 million or $1,250,000
None
$2 million
None
None
$2.5 million
None
None
$4 million
$3.6–4 million
None
None
None
None
$3 million
None
$3 million
None
None
None
None
None
None
None
None
None
$3 million
None
None
None
None
$4.4–6 million
None
None
None
None
None
None
None
None
None
None
None
$4 million
None
$5 million
None
None
None
None
$5 million
None
None
None
None
None
None
$4 million
None
None
None
$6.3 million
None
None
None
None
None
None
None
None
$5 million
None
None
None
None
$8 million
None
None
None
None
None
None
AU$1 million
None
None
None
None
$5 million
None
None
$7.5 million
None
$10 million
None
None
$3.5 to 4 million
None
None
None
$5.25 million
$20 million
$4.5 million
$9 million
None
$6-8 million
$20 million
None
None
$18 million
$12 million
$14 million
$10 million
$17 million
$5 million
$8 million
$20 million
$11 million
$28 million
$44 million
$8 million
$7.5 million
$14 million
$9 million
None
A$8.7 million
$31 million
$18 million
$5 million
$40 million
$20 million
None
$14 million
60 million Norwegian Kroner (around $8.7 million in 1989)
None
$35–40 million
$25 million
$15 million
$32 million
$14 million
$28 million
$12 million
None
None
$11 million
$28 million
$17 million
$30 million
None
$13 million
None
None
$5 million
$45 million
$31 million
None
$22 million
$30 million
None
None
$22 million
['$32 million', '(estimated)']
$18 million
$55 million
$24 million
$15 million
$12 million
None
$30 million
None
$31 million
None
$38 million
$70 million
None
$15 million
None
$67 million
None
$32 million
$7 million
$85 million
$55 million
$3 million
None
$16 million
None
$80 million
$30 million
None
$24 million
$90 million
$15 million
None
None
None
$30 million
$40–120 million
$90 million
$65 million
$5 million
None
$130 million
$75–90 million
None
$10 million
None
$90 million
$80–85 million
$15 million –$30 million
None
$4,000,000 (estimated)
$127.5 million
$65 million
None
None
$30 million
$85 million
$100 million
$23 million
None
$90–120 million
$26 million
$25 million
$115 million
None
$33 million
$20 million
None
None
$22 million
$80 million
None
$35 million
None
$15 million
$65 million
$140 million
None
$20 million
$12 million
$46 million
$13 million
$17 million
$17 million
None
$94 million
$140 million
$26 million
None
None
$46 million
$90 million
None
$10 million
$28 million
None
$15 million
None
$110 million
None
$110 million
None
$45 million
None
$92–145 million
None
$100 million
None
None
$20 million
$56 million
$25 million
None
$50 million
$35 million
$35 million
None
None
$25 million
$150 million
$180 million
None
$30 million
$1 million
None
$40 million
$50 million
$80 million
$120 million
None
$225 million
$30 million
None
$24 million
$12 million
None
$8 million
$17 million
$150 million
$300 million
$150 million
None
$25 million
None
$22 million
$85 million
$130 million
$7 million
$25 million
$225 million
$180 million
None
$20 million
None
$11 million
None
$50 million
$150 million
$80 million
None
$50 million
$30 million
$47 million
None
$175 million
None
$150 million
None
$30—$35 million
$8 million ( ₽ 350 million)
$175–200 million
$35 million
$105 million
$150 –$200 million
None
$80 million
$150–200 million
$200 million
$150 million
None
$30—$35 million
$35 million
None
$260 million
$170 million

None
None
$150 million
None
$5 million
$8 million
['$410.6 million (gross)', '$378.5 million (net)']
$200 million
$30 million
None
$45 million
None
['$306.6 million (gross)', '$263.7 million (net)']
$5 million
None
$185 million
$25 million
None
$39 million
$30—35 million
$165 million
$215 million
None
$200 million
$225–250 million
$50 million
None
$150 million
$35 million
$50 million
None
$5 million
$25 million
$180–263 million
$50 million
(US$2.9 million)
$28 million
$165 million
$50 million
$17 million
None
$90 million
$5–10 million
$180–190 million
$175 million

$175–200 million
$70–80 million
$150 million
$175–177 million
None
$170 million
$200 million
$140 million
$65 million
$15 million
$150–175 million
(US$8.8 million)
$8 million
$160–255 million
$5–10 million
$230–320 million
$175 million
None
131 crore
['~$8 million', '₽', '370 million']
$175–225 million
$100–130 million
$200 million
$65-70 million
$120–133 million
$175 million
$130 million
$170 million
None
$183 million
$200 million
$250–260 million
$186 million
$60 million
None
$150 million
$40 million
$42 million
$175–200 million
None
None
None
$125 million
$12.5 million (stage production)
None
$24 million
None
$200 million
None
$26 million
$150 million
₽650 million
None
$100 million+
$100–200 million
None
$200 million
$120–150 million
None
₽454 million
None
$175 million
None
$36 million
None
~$70 million
None
$200 million
None
$150 million
$40 million
None
$135–180 million
None
None
None
None
None
$297 million (reported) $240.2 million (net)
$200 million
None
$295–300 million
$150 million
None
$175–200 million
None
None
None
$209 million
None
$150–175 million
None
None
None
None
$28 million
$858,000
None
$9 million
$85 million
$70 million
$75–90 million
$130 million
None
$18 million or $25 million
None
$4 million
['$15,000,000', '(1 film)']
$35–40 million
$11—15 million
None
$150 million

In [8]:
import re

amounts = r"thousand|million|billion"
number = r"\d+(,\d{3})*\.*\d*"

word_re = rf"\${number}(-|\sto\s|–)?({number})?\s({amounts})"
value_re = rf"\${number}"

def word_to_value(word):
    value_dict = {"thousand": 1000, "million": 1000000, "billion": 1000000000}
    return value_dict[word]

def parse_word_syntax(string):
    value_string = re.search(number, string).group()
    value = float(value_string.replace(",", ""))
    word = re.search(amounts, string, flags=re.I).group().lower()
    word_value = word_to_value(word)
    return value*word_value

def parse_value_syntax(string):
    value_string = re.search(number, string).group()
    value = float(value_string.replace(",", ""))
    return value

'''
money_conversion("$12.2 million") --> 12200000 ## Word syntax
money_conversion("$790,000") --> 790000        ## Value syntax
'''
def money_conversion(money):
    if money == "N/A":
        return None

    if isinstance(money, list):
        money = money[0]
        
    word_syntax = re.search(word_re, money, flags=re.I)
    value_syntax = re.search(value_re, money)

    if word_syntax:
        return parse_word_syntax(word_syntax.group())

    elif value_syntax:
        return parse_value_syntax(value_syntax.group())

    else:
        return None

In [9]:
for movie in movie_info_list:
    movie['Budget (float)'] = money_conversion(movie.get('Budget', "N/A"))
    movie['Box office (float)'] = money_conversion(movie.get('Box office', "N/A"))

In [10]:
money_conversion(str(movie_info_list[0]["Budget"]))

1500000.0

### convert dates into Datetime object

In [11]:
print([movie.get('Release date', 'N/A') for movie in movie_info_list])

['N/A', 'N/A', ['November 13, 1940'], ['June 27, 1941'], 'N/A', 'N/A', 'N/A', ['July 17, 1943'], 'N/A', 'N/A', 'N/A', ['September 27, 1947'], 'May 27, 1948', 'N/A', ['October 5, 1949'], 'N/A', 'N/A', 'N/A', 'N/A', ['February 5, 1953'], ['July 23, 1953 (United States)'], ['November 10, 1953'], 'N/A', ['August 17, 1954'], ['December 23, 1954'], 'May 25, 1955', ['June 22, 1955'], ['September 14, 1955'], 'December 22, 1955', 'June 8, 1956', ['July 18, 1956'], ['September 4, 1956'], ['December 20, 1956'], 'June 19, 1957', 'August 28, 1957', ['December 25, 1957'], ['July 8, 1958'], ['August 12, 1958'], ['December 25, 1958'], ['January 29, 1959'], ['March 19, 1959'], 'N/A', ['November 10, 1959'], 'January 21, 1960 ( Sarasota, FL )', ['February 24, 1960'], 'May 19, 1960', 'N/A', ['November 1, 1960'], ['December 21, 1960'], ['January 25, 1961'], 'March 16, 1961', ['June 21, 1961'], ['July 12, 1961'], ['July 17, 1961'], ['December 14, 1961'], 'April 5, 1962', ['May 17, 1962'], ['June 6, 1962'], 'September 26, 1962', ['November 7, 1962 (Los Angeles)'], 'N/A', ['January 16, 1963'], ['March 29, 1963 (U.S.)'], ['June 1, 1963'], ['July 7, 1963'], 'November 20, 1963', 'N/A', ['March 12, 1964'], ['February 11, 1964 (Los Angeles)'], 'N/A', 'N/A', 'N/A', 'November 10, 1964', ['December 18, 1964'], ['August 18, 1965 (Los Angeles)'], ['December 2, 1965'], 'N/A', 'N/A', 'October 1, 1966', ['December 1, 1966'], ['February 8, 1967 (San Francisco)'], ['June 15, 1967'], ['July 12, 1967'], ['October 18, 1967'], ['October 18, 1967'], 'N/A', ['February 8, 1968'], ['March 21, 1968 ( Radio City Music Hall )'], ['June 26, 1968'], ['December 20, 1968'], 'N/A', ['March 21, 1969'], ['June 11, 1969'], ['December 31, 1969'], ['February 11, 1970'], 'July 1, 1970', ['December 15, 1970'], 'N/A', ['March 17, 1971'], 'June 22, 1971', ['June 30, 1971'], 'N/A', ['March 22, 1972 (US)'], 'July 12, 1972', ['July 5, 1972'], ['October 18, 1972'], ['December 22, 1972'], 'February 1, 1973', ['March 23, 1973'], ['June 20, 1973'], ['November 8, 1973'], ['December 14, 1973'], ['June 6, 1974'], ['July 31, 1974'], ['August 1, 1974'], 'December 20, 1974 (with Winnie the Pooh and Tigger Too )', ['February 6, 1975'], ['March 21, 1975 (United States)'], ['July 1, 1975'], ['July 9, 1975'], ['October 8, 1975'], ['1948–1960'], 'December 25, 1975', ['February 11, 1976 (Los Angeles)'], ['July 1, 1976'], ['July 7, 1976'], ['December 16, 1976'], 'N/A', 'N/A', ['March 11, 1977'], ['June 22, 1977'], ['June 24, 1977'], ['November 3, 1977'], ['December 16, 1977'], ['March 10, 1978'], ['June 30, 1978 (New York)'], 'July 5, 1978', 'February 9, 1979', ['June 27, 1979'], 'N/A', 'N/A', ['February 8, 1980'], 'N/A', ['June 27, 1980'], ['July 9, 1980 (Los Angeles)'], 'N/A', 'February 11, 1981 (Los Angeles)', 'March 20, 1981', ['June 26, 1981'], ['July 10, 1981'], ['August 7, 1981'], ['February 5, 1982'], ['July 9, 1982'], ['July 30, 1982'], ['March 11, 1983'], ['April 29, 1983 (United States)'], 'N/A', ['June 21, 1985 (United States)'], ['July 24, 1985'], ['September 27, 1985'], ['November 22, 1985'], ['July 2, 1986'], ['August 1, 1986'], ['June 5, 1987'], ['24 March 1988 (Australia)'], ['November 18, 1988'], ['June 23, 1989'], 'August 18, 1989', ['November 17, 1989'], ['August 3, 1990'], ['November 16, 1990'], ['January 18, 1991'], 'N/A', ['May 24, 1991'], ['June 21, 1991'], 'N/A', ['April 10, 1992'], ['July 17, 1992'], ['October 2, 1992'], ['November 11, 1992'], ['December 11, 1992'], 'February 3, 1993', ['March 12, 1993'], ['April 2, 1993'], ['July 16, 1993'], ['October 1, 1993'], ['November 12, 1993'], ['January 14, 1994'], ['February 11, 1994'], ['March 25, 1994'], ['April 14, 1994'], ['May 20, 1994'], ['June 15, 1994 (United States)'], ['July 15, 1994'], ['October 28, 1994'], 'N/A', ['December 25, 1994'], ['January 31, 1995'], ['February 17, 1995'], ['March 3, 1995'], ['March 24, 1995'], ['April 7, 1995'], 'N/A', ['July 28, 1995'], ['August 11, 1995'], ['September 27, 1995'], 'N/A', 'N/A', ['December 22, 1995'], ['February 16, 1996'], ['March 8, 1996'], 'N/A', 'N/A', ['August 13, 1996'], ['August 30, 1996'], ['October 4, 1996'], 'N/A', ['February 14, 1997'], 'N/A', 'March 18, 1997', ['June 13, 1997 (United States)'], ['July 16, 1997'], ['August 1, 1997'], ['August 5, 1997'], ['October 10, 1997'], ['November 11, 1997'], 'N/A', ['December 25, 1997'], 'February 17, 1998', ['March 27, 1998 (United States)'], 'N/A', 'N/A', ['August 25, 1998'], 'September 29, 1998', ['October 27, 1998'], ['November 13, 1998'], 'N/A', ['December 25, 1998'], ['February 12, 1999'], ['March 26, 1999'], 'N/A', 'N/A', ['July 23, 1999'], ['August 17, 1999'], 'N/A', ['November 9, 1999'], 'N/A', 'N/A', ['February 11, 2000'], 'N/A', ['March 10, 2000'], 'N/A', ['July 7, 2000'], ['August 8, 2000 (United States)'], ['September 19, 2000'], ['September 29, 2000'], ['November 22, 2000 (United States)'], 'N/A', 'N/A', ['February 27, 2001'], 'N/A', 'N/A', ['October 5, 2001'], 'N/A', ['November 6, 2001'], ['January 18, 2002'], 'N/A', ['February 26, 2002'], 'N/A', ['March 29, 2002'], 'N/A', ['July 23, 2002'], 'N/A', 'September 3, 2002', ['October 11, 2002'], 'N/A', 'N/A', ['January 21, 2003'], ['February 14, 2003'], ['March 11, 2003'], 'N/A', 'N/A', ['April 18, 2003 (United States)'], ['May 2, 2003 (United States)'], ['May 20, 2003'], 'N/A', 'N/A', 'N/A', ['August 26, 2003'], ['October 21, 2003'], 'N/A', ['November 26, 2003'], ['December 25, 2003'], ['January 16, 2004'], ['February 6, 2004'], 'N/A', ['February 20, 2004'], ['March 9, 2004'], 'N/A', ['April 22, 2004'], ['June 16, 2004'], ['July 2, 2004'], ['August 11, 2004'], ['August 17, 2004'], 'N/A', ['November 9, 2004'], ['November 19, 2004'], ['January 28, 2005'], 'N/A', 'N/A', ['March 4, 2005'], ['March 18, 2005'], ['June 14, 2005'], 'N/A', ['July 29, 2005'], 'N/A', ['August 30, 2005'], ['September 13, 2005'], ['September 30, 2005'], 'N/A', 'N/A', 'December 13, 2005', 'January 13, 2006', ['January 27, 2006'], 'N/A', ['February 17, 2006 (United States)'], ['March 10, 2006'], ['April 14, 2006'], 'N/A', 'N/A', 'N/A', ['August 25, 2006'], ['August 29, 2006'], 'N/A', ['November 3, 2006'], ['December 12, 2006'], ['February 6, 2007'], ['February 16, 2007'], 'N/A', 'N/A', 'N/A', 'N/A', ['August 3, 2007'], ['August 28, 2007'], 'N/A', 'N/A', ['December 21, 2007'], 'February 1, 2008', ['March 7, 2008'], 'N/A', 'N/A', ['26 August 2008'], 'N/A', 'October 17, 2008', 'N/A', 'N/A', ['October 28, 2008'], 'N/A', ['December 25, 2008'], ['February 27, 2009'], 'N/A', ['April 10, 2009'], 'N/A', 'N/A', 'N/A', ['19 February 2009 ( Germany )'], ['July 24, 2009'], ['2009'], ['October 27, 2009 (United States)'], ['October 29, 2009'], 'N/A', ['November 25, 2009'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', ['8 October 2010'], 'N/A', 'N/A', ['14 January 2011 (India)'], ['February 1, 2011'], ['17 February 2011 ( Germany )'], 'N/A', ['22 April 2011'], 'N/A', ['April 29, 2011'], 'N/A', 'N/A', 'N/A', ['September 20, 2011'], 'N/A', ['January 31, 2012'], 'N/A', 'N/A', ['25 May 2012'], 'N/A', ['August 15, 2012'], ['September 18, 2012'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', ['August 27, 2013'], 'N/A', 'N/A', 'N/A', 'N/A', ['April 18, 2014 (United States)'], 'N/A', 'N/A', 'N/A', ['19 September 2014'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', ['April 17, 2015 (United States)'], 'N/A', 'N/A', ['19 June 2015'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', ['26 January 2005'], 'N/A', 'N/A', 'N/A', 'N/A', ['June 30, 2017 (United States)'], ['14 July 2017'], ['October 29, 2017 ( Russia )'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', ['April 17, 2019 (United States)'], 'N/A', 'N/A', 'N/A', ['October 18, 2019'], ['November 12, 2019 (United States)'], ['November 12, 2019 ( Disney+ )'], 'N/A', ['December 20, 2019'], 'N/A', 'N/A', ['March 13, 2020'], 'N/A', ['April 3, 2020'], ['June 12, 2020'], ['July 3, 2020'], ['July 31, 2020'], ['August 14, 2020'], ['August 21, 2020 (United States)'], 'N/A', ['December 4, 2020'], ['December 11, 2020 (United States)'], 'N/A', 'N/A', ['February 19, 2021'], ['March 5, 2021'], 'N/A', 'N/A', 'N/A', 'N/A', ['December 3, 2021'], ['23 December 2021'], ['January 28, 2022 (North America)'], 'N/A', 'N/A', 'N/A', ['April 22, 2022'], 'N/A', 'N/A', 'N/A', ['June 24, 2022'], ['September 8, 2022'], ['September 30, 2022'], 'N/A', 'N/A', 'December 2, 2022', ['December 9, 2022'], ['March 10, 2023'], ['April 28, 2023'], ['May 12, 2023'], 'N/A', 'N/A', ['June 23, 2023'], 'N/A', 'N/A', ['November 17, 2023'], 'N/A', 'December 8, 2023', ['June 14, 2024'], ['December 20, 2024'], ['March 21, 2025'], ['June 13, 2025'], 'N/A', ['January 19, 2024 ( Sundance )'], 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '1950–present', ['August 1, 1986'], ['June 13, 1997 (United States)'], 'N/A', ['July 23, 1999'], ['December 21, 2007'], 'N/A', ['June 6, 1986 (United States)'], 'N/A', 'N/A', '1961– present', ['June 21, 1991'], ['November 25, 1987'], 'N/A', 'N/A']

In [12]:
from datetime import datetime

dates = [movie.get('Release date', 'N/A') for movie in movie_info_list]

def clean_date(date):
    return date.split("(")[0].strip()

def date_conversion(date):
    if isinstance(date, list):
        date = date[0]
        
    if date == "N/A":
        return None
        
    date_str = clean_date(date)

    fmts = ["%B %d, %Y", "%d %B %Y"]
    for fmt in fmts:
        try:
            return datetime.strptime(date_str, fmt)
        except:
            pass
    return None

In [13]:
for movie in movie_info_list:
    movie['Release date (datetime)'] = date_conversion(movie.get('Release date', 'N/A'))

In [14]:
movie_info_list[50]

{'title': 'The Absent-Minded Professor',
 'Directed by': 'Robert Stevenson',
 'Screenplay by': 'Bill Walsh',
 'Based on': ['"A Situation of Gravity"', 'by', 'Samuel W. Taylor'],
 'Produced by': ['Walt Disney'],
 'Starring': ['Fred MacMurray',
  'Nancy Olson',
  'Keenan Wynn',
  'Tommy Kirk',
  'Leon Ames',
  'Elliott Reid',
  'Edward Andrews',
  'Wally Brown',
  'Alan Carney',
  'Forrest Lewis',
  'James Westerfield',
  'Ed Wynn'],
 'Cinematography': 'Edward Colman',
 'Edited by': 'Cotton Warburton',
 'Music by': 'George Bruns',
 'Production company': 'Walt Disney Productions',
 'Distributed by': 'Buena Vista Distribution',
 'Release date': 'March 16, 1961',
 'Running time': '97 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Box office': '$25.3 million',
 'Running time (int)': 97,
 'Budget (float)': None,
 'Box office (float)': 25300000.0,
 'Release date (datetime)': datetime.datetime(1961, 3, 16, 0, 0)}

In [15]:
import pickle

In [17]:
with open('data.pkl','wb') as f:
    pickle.dump(movie_info_list,f)